const area = [
    {
        id: 'shanghai',
        name: '上海',
        x: 100,
        y: 100,
        p: 'AgqCJQgPgSgHgCIgBAAQAMgHAHgOQAGgNABgQQABgLgDgUQgCgWAAgJQAAgNAEgdQAFgcgBgPIgEgqQADAFAGADQAGACAFgCIAEgiQAEgBADADQADAEABAFIACAJQABAGACACQADACAGAAQAHAAADABQAGADADAOQAEANAGACQADABAIgBQAHgBADACQAJAFgFANIgEAJIgDAKIgBAGQAAADgCACIgIADQgHACAAAPIABAaQAAASAJAFIAJAFQAEADABAJQABAcgDAZIgBAFQgSgDgWAKQgSAJgOAQIgJAIIgEABQgHAAgKgMg',
        msg: '中共一大'
    },
    {
        id: 'beijing',
        name: '北京',
        x: 200,
        y: 200,
        p: 'AgqCJQgPgSgHgCIgBAAQAMgHAHgOQAGgNABgQQABgLgDgUQgCgWAAgJQAAgNAEgdQAFgcgBgPIgEgqQADAFAGADQAGACAFgCIAEgiQAEgBADADQADAEABAFIACAJQABAGACACQADACAGAAQAHAAADABQAGADADAOQAEANAGACQADABAIgBQAHgBADACQAJAFgFANIgEAJIgDAKIgBAGQAAADgCACIgIADQgHACAAAPIABAaQAAASAJAFIAJAFQAEADABAJQABAcgDAZIgBAFQgSgDgWAKQgSAJgOAQIgJAIIgEABQgHAAgKgMg',
        msg: '北京啦啦啦啦'
    }
]

export default area